# Problem 2
# 19 October 2001
# 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib(n)
  n < 2 ? n : fib(n-1) + fib(n-2)
end

i = 0
array = []
while (r = fib(i)) < 4_000_000
  array << r if (r % 2).zero?
  i += 1
end

puts array.inject(:+)
